name: "building-genai-apps"
services:
  langflow:
    image: langflowai/langflow:v1.0.19.post2
    container_name: app_langflow
    ports:
      - "7860:7860"
    depends_on:
      - postgres
      - qdrant
    env_file: ".env"
    volumes:
      - langflow-data:/app/langflow
      - langflow-config:/app/config
      - ./langflow_custom_components/:/app/components/
    networks:
      node-network:
        aliases:
          - langflow

  postgres:
    image: postgres:16
    container_name: app_postgres
    env_file: ".env"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      node-network:
        aliases:
          - postgres

  qdrant:
    container_name: app_qdrant
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant-data:/qdrant/storage
    networks:
      node-network:
        aliases:
          - qdrant

  ollama:
    container_name: app_ollama
    image: ollama/ollama:latest
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      node-network:
        aliases:
          - ollama

  streamlit:
    image: streamlit-app
    env_file: 
      - .env
      - streamlit.env
    container_name: app_streamlit
    ports:
      - "8501:8501"
    depends_on:
      - langflow
    networks:
      - node-network

volumes:
  postgres-data:
  langflow-data:
  langflow-config:
  qdrant-data:
  ollama:

networks:
  node-network:
    driver: bridge